### ISSUE TITLE
TCS-Reader Question

### ISSUE THREAD

**Issue by manuelkamp** [peteh/doorman#1]
Hi, can you please explain to me how exactly the TCS Reader works? Unfortunately I am not very familiar with the used language in this project as is. As I am working on a similar project (but on raspberry pico with micropython), and my approach is not really working (I get a different message every time I ring my bell), I appreciate any help and/or explanation. What really confuses me is the fact, that one message I have recorded seems to be the correct one, If I am writing this message to the bus, my bell rings. But as I said, my reader reads a different message every time (and therefore it is not reliable). thank you very much!

**Comment by peteh** [comment]
Hi, 

you can start with the youtube video from the credits from me readme. I took the code from these projects for reading the data. 

> TCSIntercomArduino different methods to read from and write to TCS bus
> Reverse Engineering video: https://www.youtube.com/watch?v=xFLoauqj9yA&t=11s
> https://github.com/atc1441/TCSintercomArduino
> 
> tcs-monitor an mqtt monitor for listening to the TCS bus
> Blog Post: https://blog.syralist.de/posts/smarthome/klingel/
> https://github.com/Syralist/tcs-monitor

My guess is that your code is not accurate enough for the timing as it's pretty important to interpret the numbers right. That's why the interrupt based routine that I use in my code is most reliable from what I've tried so far.

**Comment by peteh** [comment]
I'll close here and reopen if there are further questions
