### ISSUE TITLE
General questions to functionality and possible problems

### ISSUE THREAD

**Issue by NonProgrammerCharacter** [peteh/doorman#11]
I had some questions regarding functions, I can split the issue if needed and I would try to add it to the Readme if that would be okay (I like documentation)

**1:**
How exactly do I create a pattern to be recognized? If I understand description on the "codes" page running on the ESP they should be a hexadezimal number, how do I write a pattern in hexadezimal, or is it meant as "if this code is detected..."?
![image](https://github.com/peteh/doorman/assets/52523571/a9848389-3427-4f38-b904-a361812f008d)

**2:**
If I understood the project-code correctly, if I press one of the "Controls" on the device in Homeassistant the ESP sends the configured code on the bus and the correlating function should happen (door opener, bell rings) right? If not the text after this can be ignored as its written with the assumption that it works that way.

Its not working for me as it does not happen with any "Control" I try to activate, no bell and no opener.
I can see that the code change on the bus but nothing else happens.

I have checked the codes multiple times and they should be correct so I dont know why it does not work.

**Comment by peteh** [comment]
> **1:** How exactly do I create a pattern to be recognized? If I understand description on the "codes" page running on the ESP they should be a hexadezimal number, how do I write a pattern in hexadezimal, or is it meant as "if this code is detected..."? 

You have to differentiate code and pattern. To be fair I didn't put much thought into it to make it intuitive especially with the wording. 

Apartment Door pattern code and entry door pattern code can be technically any code you want. 
If the code is detected on the bus in the defined pattern, it will trigger the sensor. 

Example: 
Entry Door pattern code: 0x1234 (entry door bell code)
Entry Door pattern (currently hard coded in the program): code, 1000ms quiet, code, 1000ms quiet, code.

So if you press the entry door bell 3 times with pause of 1 second it will trigger the Entry Door pattern detected sensor AND also trigger the Door opener. 

For the apartment door pattern it will only trigger the apartment door pattern detected sensor because there is no door opener for that. 

The pattern itself is currently hard coded and defines the pause in milliseconds that should be detected between two codes of the pattern: 
```cpp
    // configure pattern detection
    patternRecognitionEntry.addStep(1000);
    patternRecognitionEntry.addStep(1000);

    // configure pattern detection
    patternRecognitionApartment.addStep(1000);
    patternRecognitionApartment.addStep(1000);
```

Currently this results in the pattern being detected if you press 3 times with a pause of 1s between each. The pause can be inaccurate to a certain extend, e.g. 800ms or 1200ms will still be considered correct. 


> **2:** If I understood the project-code correctly, if I press one of the "Controls" on the device in Homeassistant the ESP sends the configured code on the bus and the correlating function should happen (door opener, bell rings) right? If not the text after this can be ignored as its written with the assumption that it works that way.

The assumption is correct. 
> 
> Its not working for me as it does not happen with any "Control" I try to activate, no bell and no opener. I can see that the code change on the bus but nothing else happens.
> 

Unfortunately it can be a bit misleading that you see the code in the bus entity. When you send a code, reading will be disabled during that time while the code is written physically to the bus. So there is actually no real code read from the bus while you send using doorman. However, the code is injected into the entity to be logically consistent. It will be shown but it wasn't physically read. As a result, if writing doesn't work, e.g. because the wire is wrongly connected, it will still show up in TCS bus. This was done because reading and writing at the same time can lead to timing issues in the controller. 

> I have checked the codes multiple times and they should be correct so I dont know why it does not work.

The reason is that writing to the bus does not work for whatever reason. 

As actual reading codes from the bus while you press the door bell or lift the handle or anything else works as I understand from your previous posts it means that only the writing part is wrong for some reason. 

To correctly set it up you should try the following. 

1. Press your actual apartment door bell outside of your apartment
2. Note the code you see on the bus, e.g. 1b8f9a41
3. Copy and paste the code into "Apartment Door Bell Code" either on the home assistant device page or on the web interface and press save
4. Press the Apartment Bell Switch of the device in homeassistant
5. Now your door bell should ring if everything works

If it's not the case you have to double check the wiring on the following path which is for writing to the bus:
![image](https://github.com/peteh/doorman/assets/918728/516344a8-4d2e-45a0-ab70-5f8d6f57abff)

- Did you wire the correct output pin of the ESP?
- Did you solder the correct resistor values?
- Are there any shorts or broken connections on the path? 
- Is the ULN2003A soldered in the correct orientation, it has a mark at the top? 
- Is it really an ULN2003A?

**Comment by NonProgrammerCharacter** [comment]
> You have to differentiate code and pattern. To be fair I didn't put much thought into it to make it intuitive especially with the wording.
> 
> Apartment Door pattern code and entry door pattern code can be technically any code you want. If the code is detected on the bus in the defined pattern, it will trigger the sensor.

Ahh ok, thats what I thought.
Yea kinda confusing, we talk about pattern for pressing the button and "Entry Door Bell Pattern" sounds alot like that, code would be a better term for it and I guess the correct one.

> Unfortunately it can be a bit misleading that you see the code in the bus entity. When you send a code, reading will be disabled during that time while the code is written physically to the bus. So there is actually no real code read from the bus while you send using doorman. However, the code is injected into the entity to be logically consistent. It will be shown but it wasn't physically read. As a result, if writing doesn't work, e.g. because the wire is wrongly connected, it will still show up in TCS bus. This was done because reading and writing at the same time can lead to timing issues in the controller.

Ahh, ok I guess thats my problem then.

> * Did you wire the correct output pin of the ESP?
Checked.
> * Did you solder the correct resistor values (you can click on the resistors in fritzing and double check the values)?
Didnt solder yet, wanted to check if it works before soldering so used a breadboard.
I used a collor picker for resistors to get the value, double checked and everything just now.
> * Are there any shorts or broken connections on the path?
Havent found any just now, rebuild everything just to be sure
> * Is the ULN2003A soldered in the correct orientation, it has a mark at the top?
Checked.
> * Double check if the GND connection of the ULN2003A is correctly wired in connects to GND
Checked.
> * Is it really an ULN2003A?
Well I bought one, on it is written "ULN2003L", I know far to less about those to know if that is compatible or not.

Rewiring it sadly didnt help, still nothing when using the controls in Homeassistant, is the problem the "ULN2003L"?

**Comment by peteh** [comment]
> Well I bought one, on it is written "ULN2003L", I know far to less about those to know if that is compatible or not.
>Rewiring it sadly didnt help, still nothing when using the controls in Homeassistant, is the problem the "ULN2003L"?

It should not if as the difference of A (long legs for through hole soldering) and L (short legs for on board flat soldering) seems to only be packaging and the chips should be identical. 

I have no good idea how to debug where it's failing though. You could post a picture  with good light and high resolution so we can check if there is another obvious issue. 

Other than that you could try to figure out in some electronics forums how to test if the ULN is doing what it should. I don't have enough electric background for that unfortunately.

**Comment by NonProgrammerCharacter** [comment]
I tried another ULN, if its broken or something as I got multiple (if im paying 18€ for delivery better get multiple) sadly didnt help.

Here is a pic, I removed the parts not used / needed atm for better overview.
I marked the green line start and ends for the same reason.
![bild (2)](https://github.com/peteh/doorman/assets/52523571/77d4d8b6-0572-4bf5-8fe7-6c74b5cf8b7c)

**Comment by peteh** [comment]
The wiring looks reasonable. 

Did you measure the resistors with a multimeter or just by color coding? 
If just by color coding I would still measure each of them with a multimeter just to be sure. 

Can you also make a screenshot of your code settings? 
For my door opener it's 00001100.

**Comment by NonProgrammerCharacter** [comment]
I did not measure all resistors, I only had to color code your graphic as it wasnt written which resisitor goes where.
They came labeld with their value so I dont think thats a problem. (I just checked all used for writing to the bus)

But I saw that the 1.2 Ohm resistors only show 0.2 on my (realy cheap) multimeter but they all do (got 20 or so) so not sure if thats a problem or just my multimeter beeing unprecise on low values.

![image](https://github.com/peteh/doorman/assets/52523571/ae439ad8-01ab-46a3-b853-ccd272b87876)

Its the same code for me.

**Comment by NonProgrammerCharacter** [comment]
> Just to make sure, you have to measure them outside of the circuit.

Oh? I didnt know that, they have 0.6 Ohm outside of the circuit.

**Comment by peteh** [comment]
Which is still weird. If you measure them as one single resistor you should have 1.2Ohm. If you measure them while they are parallel you should measure 0.6Ohm. 

If you measure just 0.6Ohm for one resistor you can just put a single resistor instead of two.

**Comment by NonProgrammerCharacter** [comment]
I realy think its my multimeter, I have two different 1.2 Ohm resistors from different shops and booth have 0.6 Ohm and some 1.5 Ohm resistors which measure 1.1 Ohm.

But I can try it anyway, I dont know what else to try besides rewiring again, maybe on a different board if there is a short.

Other than that im kinda clueless what alse to try besides soldering it and hoping it works.

**Comment by peteh** [comment]
I also don't know how to further debug. 

You could still try a different power supply for the d1 mini. Some people had issues with power supply and I probably should add a capacitor to the circuit in general. 

The bus writing part is based on this project: 
https://github.com/atc1441/TCSintercomArduino

You could try the single sketches from that repo and check if they work and maybe the creator has some more ideas what could be wrong. 

You can run the sketches from platformio if you add 
```
#include <Arduino
```
to the top of the ino files and rename them to main.cpp in a new platformio project.

**Comment by NonProgrammerCharacter** [comment]
Well I was kinda demotivated after spending so much time on it and not even knowing why it didnt work so I picked it back up today when a colleague came over and was interested in it (not the problem) and after setting it all up again und plugin Homeassistant back in it just worked.
I didnt change anything from my last attempt so im stumped what the problem was, I guess maybe a falty connection on the board or something.

I tested all the controls and everything worked without a problem.

> You could still try a different power supply for the d1 mini. Some people had issues with power supply and I probably should add a capacitor to the circuit in general.

Dont think that should be possible in my case, im using a powerbank for it with up to 30 watts charging power.

Soo, gonna solder it soon and see if it still works.

**Comment by peteh** [comment]
Awesome! 

Thank you for the feedback. I'm not sure how long the power bank will last though. I haven't put any effort into reducing power consumption.

**Comment by NonProgrammerCharacter** [comment]
Its only for testing purposes, I have a 24V transformator in my fuse box I will use I just wanted to get it working so I removed all unneeded components from the board.

The friend already expressed interest in building his own.

**Comment by peteh** [comment]
@NonProgrammerCharacter I think this topic can be closed now. If there are other issues, then just open a new one.
